twig:
    file_name_pattern: '*.twig'
    globals:
        APP_ASSETS_BASE_URL: '%env(APP_ASSETS_BASE_URL)%'
        APP_ASSET_UPLOAD_IMAGE: '%env(APP_ASSET_UPLOAD_IMAGE)%'
when@test:
    twig:
        strict_variables: true
