vich_uploader:
    db_driver: orm

    mappings:
        image_upload: # C'est le nom de notre "mapping" (il doit correspondre à celui dans l'entité Image)
            uri_prefix: /uploads/images # Le chemin public pour accéder aux images via le navigateur
            upload_destination: '%kernel.project_dir%/public/uploads/images' # Le chemin physique sur le serveur où les fichiers seront stockés
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer # La stratégie pour nommer les fichiers (ici, un nom unique et intelligent)
            delete_on_remove: true # Supprimer le fichier quand l'entité Image est supprimée
            delete_on_update: true # Supprimer l'ancien fichier quand un nouveau est uploadé

