# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.upload_dir: '%kernel.project_dir%/public/uploads/images'
    app.vich_image_upload_destination: '%kernel.project_dir%/public/uploads/images'
    app.assets_base_url: '%env(APP_ASSETS_BASE_URL)%'

services:
    Imagine\Gd\Imagine: ~
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    session.handler.pdo:
        class: Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        arguments:
            - '%env(DATABASE_URL)%'
            - { db_table: sessions, db_id_col: sess_id, db_data_col: sess_data, db_lifetime_col: sess_lifetime, db_time_col: sess_time }
                
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    App\Service\ImageProcessor:
        arguments:
            $projectDir: '%kernel.project_dir%'

    #App\EventSubscriber\EasyAdminImageUploadSubscriber:
    #    public: true # Force-le à être public pour le débogage
    #    tags: ['kernel.event_subscriber'] # Balise-le explicitement

    App\EventListener\ImageUploadListener:
        arguments:
            $imageProcessor: '@App\Service\ImageProcessor'
            # Passez le paramètre défini plus haut comme valeur pour $uploadDestination
            $uploadDestination: '%app.vich_image_upload_destination%'
        tags:
            #- { name: kernel.event_listener, event: vich_uploader.pre_upload, method: onVichPreUpload }
            #- { name: kernel.event_listener, event: vich_uploader.post_upload, method: onVichPostUpload }  
        public: false 
    App\EventListener\ImageFormatsDeletionSubscriber:
        arguments:
            $filesystem: '@Symfony\Component\Filesystem\Filesystem'
            $uploadDir: '%app.upload_dir%'
        tags:
            - { name: doctrine.event_subscriber, connection: default }
    App.menu_builder:
        class: App\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main_menu}
    
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
